# Generated by Django 6.0 on 2025-12-25 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pet",
            name="image",
            field=models.ImageField(upload_to="Pet_Uploads/"),
        ),
    ]
