# Generated by Django 6.0 on 2025-12-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Accounts", "0002_adminuser"),
    ]

    operations = [
        migrations.AddField(
            model_name="adminuser",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
